Added NativeElement
jacksondunstan/NativeCollections pull request #2
Opened 2018-12-19 13:43 UTC by Tom01098

I've created and added a NativeElement container - it's just a copy of [my repo](https://github.com/Tom01098/NativeElement-UnityCollections). The intention is to allow a single blittable element to be passed into a job.

2018-12-20 17:38 UTC, jacksondunstan requested changes
Hi @Tom01098,

This looks like a nice addition to NativeCollections! Before I merge though, I'd like to see a few changes made so that it better fits in with the other types (e.g. `NativeLinkedList`) so I've pointed out a number of issues in the file. Most of them should be trivial to change as they mostly relate to consistent styling, but in a few cases they do relate to functionality. One piece that's completely missing though is unit tests. Every other type is thoroughly tested and the same should be true here.

Thanks again for the submission,
-Jackson

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +/// NativeElement is a wrapper for a single blittable element to be passed between managed and unmanaged code in jobs
Line is longer than 80 characters.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +/// <typeparam name="T">The blittable type to be stored</typeparam>
XML elements should be separated like this:

```csharp
/// <summary>
/// The summary
/// </summary>
/// 
/// <typeparam name="T">
/// Explain the type param
/// </typeparam>
```

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +public unsafe struct NativeElement<T> : IDisposable where T : unmanaged
`where` goes on the next line, indented.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    // The pointer to the element
Describe with an xml-doc style comment.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    T* m_ptr;
Fields should be named like `m_MyVar` for consistency with Unity-mandated field names like `m_MinIndex`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    // Safety
Describe with an xml-doc style comment.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    AtomicSafetyHandle m_Safety;
Should be explicitly marked `private`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    [NativeSetClassTypeToNullOnSchedule]
Describe with an xml-doc style comment.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    DisposeSentinel m_DisposeSentinel;
Should be explicitly marked `private`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    // The allocator label
Describe with an xml-doc style comment.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    Allocator m_AllocatorLabel;
Should be explicitly marked `private`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    Allocator m_AllocatorLabel;
Rename to `m_Allocator` for consistency with other types.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    // Constructor which only takes a label and then calls the main constructor with an instance of T
Describe with an xml-doc style comment.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    public NativeElement(Allocator label) : this(new T(), label) { }
Remove in favor of a default parameter to the other constructor: `T element = default(T)`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    // Main constructor logic that takes an element and a label
Describe with an xml-doc style comment.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +        // Label check
Reword to "Require a valid allocator" as in other types.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +#if ENABLE_UNITY_COLLECTIONS_CHECKS
Remove `#if`...`#endif` wrapping as this check should occur all the time.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +            throw new ArgumentException("NativeElement must be allocated using Job, TempJob or Persistent");
Add curly braces around this line.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +            throw new ArgumentException("NativeElement must be allocated using Job, TempJob or Persistent");
Change to match other types in the project:
```csharp
throw new ArgumentException(
	"Allocator must be Temp, TempJob or Persistent",
	"allocator");
```

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +        // Label set
Reword to match other types:
```csharp
// Store the allocator for future allocation and deallocation
// operations
```

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +        DisposeSentinel.Create(out m_Safety, out m_DisposeSentinel, 0, label);
Support both Unity 2018.2 and Unity 2018.3 versions of this function as other types do:
```csharp
#if UNITY_2018_3_OR_NEWER
	DisposeSentinel.Create(
		out m_Safety,
		out m_DisposeSentinel,
		0,
		allocator);
#else
	DisposeSentinel.Create(out m_Safety, out m_DisposeSentinel, 0);
#endif
```

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +        Element = element;
Remove property function call and safety check by replacing with `m_Ptr = element`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +        // Create element to avoid unitialised data
Reword for improved accuracy. For example, `Set the initial value.`

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    // Property for the Element stored
Describe with an xml-doc style comment.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    public T Element
Rename to `Value` for consistency with `NativeIntPtr`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    T* m_ptr;
Rename to `m_Buffer` for consistency with `NativeIntPtr` and to support `[NativeContainerSupportsDeallocateOnJobCompletion]`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +[DebuggerDisplay("{Element}")]
Add `[NativeContainerSupportsDeallocateOnJobCompletion]` for consistency with `NativeIntPtr` and to allow this feature.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    }
Add a `RequireBlittable` call like in other types.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +#if ENABLE_UNITY_COLLECTIONS_CHECKS
Move this check to a `RequireReadAccess` function.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +            // Return the element
Remove or reword comment as it currently describes what is obvious.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +            // Set the element
Remove or reword comment as it currently describes what is obvious.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +#if ENABLE_UNITY_COLLECTIONS_CHECKS
Move this check to a `RequireWriteAccess` function.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    // Dispose of all resources
Replace with a copy of `NativeIntPtr.Dispose` to improve commenting, support for both 2018.2 and 2018.3, add `[WriteAccessRequired]`, add `RequireWriteAccess`, and set `m_Buffer` to `null`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +        set
Add `[WriteAccessRequired]`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +}
Add `IsCreated` property.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    public NativeElement(T element, Allocator label)
Rename `element` to `initialValue` for consistency with other types, move it to the end of the parameter list, and add a default value: `T initialValue = default(T)`.

2018-12-20 17:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    public NativeElement(T element, Allocator label)
Rename `label` to `allocator` for consistency with other types.

2018-12-20 18:29 UTC, Tom01098 commented
Hey, thanks for the detailed review :) I'll work on it - not familiar with NUnit though so I might be forever ;)

2018-12-30 18:25 UTC, Tom01098 commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    }
Hi, I've made all the other changes you requested, but this one is a bit confusing to me - the type parameter T is already constrained to be unmanaged - would you like me to change it to be constrained to a struct and then have a blittable check?

2019-01-04 03:38 UTC, jacksondunstan commented on JacksonDunstanNativeCollections/NativeElement.cs
> +    }
Yes, that's necessary for compatibility with Unity 2018.2 when C# 7 wasn't yet supported and for consistency with Unity's types such as `NativeArray<T>`.

2019-01-04 03:43 UTC, jacksondunstan commented
> Hey, thanks for the detailed review :) I'll work on it - not familiar with NUnit though so I might be forever ;)

Hi @Tom01098, please take your time! :) NUnit is well worth learning as other xUnit frameworks are common in other languages such as Java and the skills learned in one tend to port well to the others.

I missed one item in my initial review: the type should be renamed to `NativePtr` for consistency with `NativeIntPtr`, `NativePerJobThreadIntPtr`, `NativeLongPtr`, and `NativePerJobThreadLongPtr` and also because it's not really an element of anything like an array but rather a pointer to a single value.

2020-03-30 16:45 UTC, torsina commented
@Tom01098 update ?

2020-04-08 19:02 UTC, Tom01098 commented
> @Tom01098 update ?

Sorry about this; I no longer work with Unity and so should have closed this PR a while ago. I assume the basic concept of what I did here still works in newer versions of the Job System.

2020-04-08 19:02 UTC, closed without merging